// OPTX site directory.
// Every searchable entry declares lookupTypes so future VIN/email/name/IP sites do
// not appear in phone results until that lookup type is enabled in the UI.
const sites = [
  // Free phone lookup sources. Major people-search sites stay near the top.
  { name: 'truepeoplesearch.com', searchUrl: 'https://www.truepeoplesearch.com/resultphone?phoneno={phone}', optOutUrl: 'https://www.truepeoplesearch.com/removal', category: 'free', lookupTypes: ['phone'] },
  { name: 'fastpeoplesearch.com', searchUrl: 'https://www.fastpeoplesearch.com/{phone_dashes}', optOutUrl: 'https://www.fastpeoplesearch.com/removal', category: 'free', lookupTypes: ['phone'] },
  { name: 'searchpeoplefree.com', searchUrl: 'https://www.searchpeoplefree.com/phone-lookup/{phone_dashes}', optOutUrl: 'https://www.searchpeoplefree.com/optout', category: 'free', lookupTypes: ['phone'] },
  { name: 'usphonebook.com', searchUrl: 'https://www.usphonebook.com/phone-search/{phone_dashes}', optOutUrl: 'https://www.usphonebook.com/opt-out', category: 'free', lookupTypes: ['phone'] },
  { name: 'thatsthem.com', searchUrl: 'https://thatsthem.com/phone/{phone_dashes}', optOutUrl: 'https://thatsthem.com/optout', category: 'free', lookupTypes: ['phone'] },
  { name: 'allpeople.com', searchUrl: 'https://allpeople.com/search?ss=&ss-e=&ss-p={phone}&ss-i=&where=&industry-auto=&where-auto=', optOutUrl: 'https://allpeople.com/removal', category: 'free', lookupTypes: ['phone'] },
  { name: 'advancedbackgroundchecks.com', searchUrl: 'https://www.advancedbackgroundchecks.com/find/phone/{phone}', optOutUrl: 'https://www.advancedbackgroundchecks.com/opt-out', category: 'free', lookupTypes: ['phone'] },
  { name: 'cyberbackgroundchecks.com', searchUrl: 'https://www.cyberbackgroundchecks.com/phone/{phone_dashes}', optOutUrl: 'https://www.cyberbackgroundchecks.com/removal', category: 'free', lookupTypes: ['phone'] },
  { name: 'fastbackgroundcheck.com', searchUrl: 'https://www.fastbackgroundcheck.com/phone/{phone_dashes}', optOutUrl: 'https://www.fastbackgroundcheck.com/optout', category: 'free', lookupTypes: ['phone'] },
  { name: 'familytreenow.com', searchUrl: 'https://www.familytreenow.com/search/genealogy/results?phoneno={phone_parentheses}', optOutUrl: 'https://www.familytreenow.com/optout', category: 'free', lookupTypes: ['phone'] },
  { name: 'zabasearch.com', searchUrl: 'https://www.zabasearch.com/phone/{phone}', optOutUrl: 'https://www.zabasearch.com/block_records', category: 'free', lookupTypes: ['phone'] },
  { name: 'peoplesearchnow.com', searchUrl: 'https://www.peoplesearchnow.com/phone/{phone_dashes}', optOutUrl: 'https://www.peoplesearchnow.com/opt-out', category: 'free', lookupTypes: ['phone'], statusOverride: 'online' },
  { name: 'usa-people-search.com', searchUrl: 'https://www.usa-people-search.com/phone/{phone_dashes}', optOutUrl: 'https://www.usa-people-search.com/removal', category: 'free', lookupTypes: ['phone'] },
  { name: 'phonebooks.com', searchUrl: 'https://www.phonebooks.com/phone-results?phone={phone_dashes}', optOutUrl: 'https://www.phonebooks.com/opt-out', category: 'free', lookupTypes: ['phone'] },
  { name: 'anywho.com', searchUrl: 'https://www.anywho.com/phone/{phone}', optOutUrl: 'https://www.spokeo.com/optout', category: 'free', lookupTypes: ['phone'] },
  { name: 'radaris.com', searchUrl: 'https://radaris.com/ng/phone/{phone}', optOutUrl: 'https://radaris.com/control-privacy', category: 'free', lookupTypes: ['phone'] },
  { name: 'smartbackgroundchecks.com', searchUrl: 'https://www.smartbackgroundchecks.com/phone/{phone}', optOutUrl: 'https://www.smartbackgroundchecks.com/optout', category: 'free', lookupTypes: ['phone'] },
  { name: 'whocalld.com', searchUrl: 'https://whocalld.com/+1{phone}', optOutUrl: 'https://whocalld.com/about#:~:text=you%20may%20email-,mail%40whocalld.com,-.', category: 'free', lookupTypes: ['phone'] },
  { name: 'callercenter.com', searchUrl: 'https://www.callercenter.com/{phone_dashes}.html', optOutUrl: 'https://www.callercenter.com/remove_name.htm', category: 'free', lookupTypes: ['phone'] },
  { name: 'spydialer.com', searchUrl: 'https://www.spydialer.com/', optOutUrl: 'https://www.spydialer.com/Consumers/', category: 'free', lookupTypes: ['phone'], manual: true },
  { name: 'calltracer.io', searchUrl: 'https://calltracer.io/number/1{phone}', optOutUrl: 'https://calltracer.io/request-removal', category: 'free', lookupTypes: ['phone'] },
  { name: 'numlookup.com', searchUrl: 'https://www.numlookup.com/', optOutUrl: 'https://www.numlookup.com/opt_out', category: 'free', lookupTypes: ['phone'], manual: true },
  { name: 'ipqualityscore.com', searchUrl: 'https://www.ipqualityscore.com/reverse-phone-number-lookup/lookup/US/{phone}', optOutUrl: 'https://www.ipqualityscore.com/contact-us', category: 'free', lookupTypes: ['phone'] },
  { name: 'searchquarry.com', searchUrl: 'https://www.searchquarry.com/phone-number-lookup/{phone}/', optOutUrl: 'https://privacyportal-eu.onetrust.com/webform/f6adb000-5a85-4ec1-a631-151c15d9d854/c3726644-a419-4170-86d8-9dfea2e9ef72', category: 'free', lookupTypes: ['phone'] },
  { name: 'youmail.com', searchUrl: 'https://directory.youmail.com/phone?phoneNumber={phone}', optOutUrl: 'https://compliance.youmail.com/submit-request', category: 'free', lookupTypes: ['phone'] },
  { name: 'nuwber.com', searchUrl: 'https://nuwber.com/search/phone?phone={phone}', optOutUrl: 'https://nuwber.com/removal/link', category: 'free', lookupTypes: ['phone'] },
  { name: '411.info', searchUrl: 'https://411.info/reverse?r={phone}', optOutUrl: 'https://411.info/contact', category: 'free', lookupTypes: ['phone'] },
  { name: 'addresses.com', searchUrl: 'https://www.addresses.com/phone/{phone}', optOutUrl: 'https://www.addresses.com/optout.php', category: 'free', lookupTypes: ['phone'] },
  { name: 'veripages.com', searchUrl: 'https://veripages.com/reverse-phone-lookup/area-code-{phone_area}/{phone_prefix}/{phone_dashes}', optOutUrl: 'https://veripages.com/inner/removal-service?s=footer', category: 'free', lookupTypes: ['phone', 'name', 'address'], urls: { phone: 'https://veripages.com/reverse-phone-lookup/area-code-{phone_area}/{phone_prefix}/{phone_dashes}', name: 'https://veripages.com/', address: 'https://veripages.com/' }, modes: { name: 'manual', address: 'manual' } },
  { name: '24counter.com', searchUrl: 'https://24counter.com/{phone}', optOutUrl: 'https://24counter.com/opt-out', category: 'free', lookupTypes: ['phone'] },
  { name: 'cellrevealer.com', searchUrl: 'https://www.cellrevealer.com/', optOutUrl: 'https://www.cellrevealer.com/Contact', category: 'free', lookupTypes: ['phone'], manual: true },
  { name: 'americaphonebook.com', searchUrl: 'https://americaphonebook.com/reverse.php', optOutUrl: null, category: 'free', lookupTypes: ['phone'], manual: true },
  { name: 'telephonedirectories.us', searchUrl: 'https://www.telephonedirectories.us/Phone/{phone}', optOutUrl: 'https://www.telephonedirectories.us/Edit_Records', category: 'free', lookupTypes: ['phone'] },
  { name: 'unmask.com', searchUrl: 'https://unmask.com/phone/{phone_dashes}/', optOutUrl: 'https://unmask.com/privacy-rights/', category: 'free', lookupTypes: ['phone'] },
  { name: 'peoplesearched.com', searchUrl: 'https://peoplesearched.com/', optOutUrl: 'https://peoplesearched.com/contact/', category: 'free', lookupTypes: ['phone', 'name', 'email', 'address'], manual: true },

  // Free future lookup sources. These stay out of phone results.
  { name: 'addresssearch.com', searchUrl: 'https://www.addresssearch.com/', optOutUrl: 'https://www.addresssearch.com/remove-info.php', category: 'free', lookupTypes: ['name', 'email', 'address'], urls: { name: 'https://www.addresssearch.com/', email: 'https://email.addresssearch.com/', address: 'https://www.addresssearch.com/' }, manual: true },
  { name: 'centeda.com', searchUrl: 'https://centeda.com/', optOutUrl: 'https://centeda.com/control/privacy', category: 'free', lookupTypes: ['name'], manual: true },
  { name: 'nationalpublicdata.com', searchUrl: 'https://nationalpublicdata.com/', optOutUrl: 'https://nationalpublicdata.com/optout.html', category: 'free', lookupTypes: ['name'], manual: true },
  { name: 'haveibeenpwned.com', searchUrl: 'https://haveibeenpwned.com/', optOutUrl: 'https://haveibeenpwned.com/OptOut', category: 'free', lookupTypes: ['email'], manual: true },
  { name: 'vpic.nhtsa.dot.gov', searchUrl: 'https://vpic.nhtsa.dot.gov/api/vehicles/DecodeVinValues/{vin}?format=json', optOutUrl: null, category: 'free', lookupTypes: ['vin'], statusUrl: 'https://vpic.nhtsa.dot.gov/decoder/' },
  { name: 'nicb.org', searchUrl: 'https://www.nicb.org/vincheck', optOutUrl: null, category: 'free', lookupTypes: ['vin'], manual: true },
  { name: 'ipinfo.io', searchUrl: 'https://ipinfo.io/{ip}', optOutUrl: null, category: 'free', lookupTypes: ['ip'] },
  { name: 'whatismyipaddress.com', searchUrl: 'https://www.whatismyipaddress.com/ip/{ip}', optOutUrl: null, category: 'free', lookupTypes: ['ip'] },
  { name: 'abuseipdb.com', searchUrl: 'https://www.abuseipdb.com/check/{ip}', optOutUrl: null, category: 'free', lookupTypes: ['ip'], statusUrl: 'https://www.abuseipdb.com/favicon.ico', statusExact: true, statusOverride: 'online' },
  { name: 'shodan.io', searchUrl: 'https://www.shodan.io/host/{ip}', optOutUrl: null, category: 'free', lookupTypes: ['ip'] },

  // Paid phone lookup sources. Major brokers and broker networks stay near the top.
  { name: 'peopleconnect.us', searchUrl: 'https://suppression.peopleconnect.us/', optOutUrl: 'https://suppression.peopleconnect.us/privacy-center', category: 'paid', lookupTypes: ['phone'], manual: true },
  { name: 'intelius.com', searchUrl: 'https://www.intelius.com/reverse-phone-lookup/', optOutUrl: 'https://app.intelius.com/privacy-center/', category: 'paid', lookupTypes: ['phone'], manual: true },
  { name: 'truthfinder.com', searchUrl: 'https://www.truthfinder.com/phone/search?phone={phone}', optOutUrl: 'https://app.truthfinder.com/privacy-center/', category: 'paid', lookupTypes: ['phone'] },
  { name: 'instantcheckmate.com', searchUrl: 'https://www.phone.instantcheckmate.com/search/?phone={phone}', optOutUrl: 'https://app.instantcheckmate.com/privacy-center/', category: 'paid', lookupTypes: ['phone'] },
  { name: 'ussearch.com', searchUrl: 'https://www.ussearch.com/search-select/', optOutUrl: 'https://app.ussearch.com/privacy-center/', category: 'paid', lookupTypes: ['phone'], manual: true },
  { name: 'whitepages.com', searchUrl: 'https://www.whitepages.com/phone/{phone}', optOutUrl: 'https://www.whitepages.com/privacy/consumer-rights', category: 'paid', lookupTypes: ['phone'] },
  { name: 'spokeo.com', searchUrl: 'https://www.spokeo.com/{phone}', optOutUrl: 'https://www.spokeo.com/optout', category: 'paid', lookupTypes: ['phone', 'name', 'email', 'address'], urls: { phone: 'https://www.spokeo.com/{phone}', name: 'https://www.spokeo.com/', email: 'https://www.spokeo.com/email-search', address: 'https://www.spokeo.com/' }, modes: { name: 'manual', email: 'manual', address: 'manual' } },
  { name: 'beenverified.com', searchUrl: 'https://www.beenverified.com/reverse-phone/', optOutUrl: 'https://www.beenverified.com/app/optout/search', category: 'paid', lookupTypes: ['phone', 'name', 'email', 'address', 'vin'], urls: { phone: 'https://www.beenverified.com/reverse-phone/', name: 'https://www.beenverified.com/', email: 'https://www.beenverified.com/', address: 'https://www.beenverified.com/', vin: 'https://www.beenverified.com/' }, modes: { phone: 'manual', name: 'manual', email: 'manual', address: 'manual', vin: 'manual' } },
  { name: 'peoplefinders.com', searchUrl: 'https://www.peoplefinders.com/', optOutUrl: 'https://www.peoplefinders.com/opt-out', category: 'paid', lookupTypes: ['phone'], manual: true },
  { name: 'peoplefinder.com', searchUrl: 'https://www.peoplefinder.com/', optOutUrl: 'https://app.intelius.com/privacy-center/', category: 'paid', lookupTypes: ['phone'], manual: true },
  { name: 'peoplesmart.com', searchUrl: 'https://www.peoplesmart.com/', optOutUrl: 'https://www.peoplesmart.com/optout', category: 'paid', lookupTypes: ['phone'], manual: true },
  { name: 'peoplelooker.com', searchUrl: 'https://www.peoplelooker.com/', optOutUrl: 'https://www.peoplelooker.com/optout', category: 'paid', lookupTypes: ['phone'], manual: true },
  { name: 'mylife.com', searchUrl: 'https://phone.mylife.com/phone-{phone_dashes}', optOutUrl: 'https://www.mylife.com/ccpa/index.pubview', category: 'paid', lookupTypes: ['phone'] },
  { name: '411.com', searchUrl: 'https://www.411.com/phone/{phone_1_dashes}', optOutUrl: 'https://www.whitepages.com/privacy/consumer-rights', category: 'paid', lookupTypes: ['phone'] },
  { name: 'numberguru.com', searchUrl: 'https://www.numberguru.com/', optOutUrl: 'https://www.numberguru.com/svc/optout/search/optouts', category: 'paid', lookupTypes: ['phone'], manual: true },
  { name: 'infotracer.com', searchUrl: 'https://infotracer.com/', optOutUrl: 'https://infotracer.com/optout/', category: 'paid', lookupTypes: ['phone'], manual: true },
  { name: 'callersmart.com', searchUrl: 'https://www.callersmart.com/search?q={phone_dashes}', optOutUrl: 'https://www.callersmart.com/data', category: 'paid', lookupTypes: ['phone'] },
  { name: 'lookups.io', searchUrl: 'https://lookups.io/phone/{phone}', optOutUrl: 'https://lookups.io/contact', category: 'paid', lookupTypes: ['phone'] },
  { name: 'findpeoplefast.net', searchUrl: 'https://findpeoplefast.net/free-phone-number-lookup', optOutUrl: 'https://findpeoplefast.net/remove-my-info', category: 'paid', lookupTypes: ['phone'], manual: true },
  { name: 'whoeasy.com', searchUrl: 'https://www.whoeasy.com/pni/q/{phone}', optOutUrl: 'https://www.whoeasy.com/optout', category: 'paid', lookupTypes: ['phone'] },
  { name: 'nationalcellulardirectory.com', searchUrl: 'https://www.nationalcellulardirectory.com/processsearch.aspx?type=1&phone={phone}', optOutUrl: 'https://www.nationalcellulardirectory.com/optout/', category: 'paid', lookupTypes: ['phone'] },
  { name: 'claritycheck.com', searchUrl: 'https://claritycheck.com/search/phone/1{phone}/email', optOutUrl: 'https://claritycheck.com/help/delete-your-account', category: 'paid', lookupTypes: ['phone'] },
  { name: 'checkpeople.com', searchUrl: 'https://checkpeople.com/reverse-phone-lookup', optOutUrl: 'https://checkpeople.com/privacy-rights', category: 'paid', lookupTypes: ['phone'], manual: true },
  { name: 'confidentialphonelookup.com', searchUrl: 'https://www.confidentialphonelookup.com/metadata_results.php?tel={phone}', optOutUrl: 'https://www.confidentialphonelookup.com/contact/', category: 'paid', lookupTypes: ['phone'] },
  { name: 'peoplesearcher.com', searchUrl: 'https://www.peoplesearcher.com/', optOutUrl: 'https://www.peoplesearcher.com/api/helper/optOutLight/search', category: 'paid', lookupTypes: ['phone'], manual: true },
  { name: 'privaterecords.net', searchUrl: 'https://www.privaterecords.net/', optOutUrl: 'https://www.privaterecords.net/api/helper/optOutLight/search', category: 'paid', lookupTypes: ['phone'], manual: true },
  { name: 'recordsfinder.com', searchUrl: 'https://recordsfinder.com/search/phone/results/?flow=phone&country=US&phone={phone_dashes}&noHit=1', optOutUrl: 'https://recordsfinder.com/optout/', category: 'paid', lookupTypes: ['phone'] },
  { name: 'courtcasefinder.com', searchUrl: 'https://courtcasefinder.com/search/loader?phone={phone_dashes}', optOutUrl: 'https://members.courtcasefinder.com/privacyform', category: 'paid', lookupTypes: ['phone'] },
  { name: 'freepeoplesearch.com', searchUrl: 'https://freepeoplesearch.com/', optOutUrl: 'https://freepeoplesearch.com/privacy-rights/', category: 'paid', lookupTypes: ['phone'], manual: true },
  { name: 'information.com', searchUrl: 'https://information.com/reverse-phone-lookup/{phone_dashes}/', optOutUrl: 'https://information.com/privacy-rights/', category: 'paid', lookupTypes: ['phone'] },
  { name: 'reversephonelookup.com', searchUrl: 'https://www.reversephonelookup.com/number/{phone}/', optOutUrl: 'https://app.intelius.com/privacy-center/', category: 'paid', lookupTypes: ['phone'] },
  { name: 'usatrace.com', searchUrl: 'https://www.usatrace.com/reverse-phone-search/{phone_dashes}/', optOutUrl: 'https://www.usatrace.com/your-privacy/', category: 'paid', lookupTypes: ['phone'] },
  { name: 'quickpeopletrace.com', searchUrl: 'https://www.quickpeopletrace.com/search/?phonesearch=1&tabid=2&teaser-phone={phone_area}&teaser-submitted=Search', optOutUrl: 'https://www.quickpeopletrace.com/contact-us/', category: 'paid', lookupTypes: ['phone'] },
  { name: 'peoplewin.com', searchUrl: 'https://peoplewin.com/{phone_dashes}', optOutUrl: 'https://www.spokeo.com/optout', category: 'paid', lookupTypes: ['phone'] },
  { name: 'peoplewhiz.com', searchUrl: 'https://www.peoplewhiz.com/', optOutUrl: 'https://www.peoplewhiz.com/optout', category: 'paid', lookupTypes: ['phone'], manual: true },
  { name: 'dobsearch.com', searchUrl: 'https://www.dobsearch.com/phone-lookup/', optOutUrl: 'https://www.dobsearch.com/contact/', category: 'paid', lookupTypes: ['phone'], manual: true },
  { name: 'lookify.io', searchUrl: 'https://lookify.io/number/{phone}', optOutUrl: 'https://lookify.io/opt-out', category: 'paid', lookupTypes: ['phone'] },
  { name: 'socialcatfish.com', searchUrl: 'https://socialcatfish.com/reverse-phone-lookup/', optOutUrl: 'https://socialcatfish.com/opt-out/?id=law_enforcement_optout', category: 'paid', lookupTypes: ['phone', 'name', 'email'], manual: true },
  { name: 'revealphoneowner.com', searchUrl: 'https://www.revealphoneowner.com/lookup/number/{phone_dashes}/', optOutUrl: 'https://www.revealphoneowner.com/data-removal/', category: 'paid', lookupTypes: ['phone'] },
  { name: 'reversephone.com', searchUrl: 'https://www.reversephone.com/', optOutUrl: 'https://www.reversephone.com/svc/optout/search/optouts', category: 'paid', lookupTypes: ['phone'], manual: true },
  { name: 'sync.me', searchUrl: 'https://sync.me/search/?number=1{phone}', optOutUrl: 'https://sync.me/unsubscribe/', category: 'paid', lookupTypes: ['phone'] },
  { name: 'unitedstatesphonebook.com', searchUrl: 'https://www.unitedstatesphonebook.com/', optOutUrl: 'https://www.unitedstatesphonebook.com/contact.php#:~:text=Removal%20Instructions', category: 'paid', lookupTypes: ['phone'], manual: true },
  { name: 'wyty.com', searchUrl: 'https://www.wyty.com/phone/', optOutUrl: 'https://www.wyty.com/remove/', category: 'paid', lookupTypes: ['phone'], manual: true },

  // Paid future lookup sources. These stay out of phone results until enabled.
  { name: 'bumper.com', searchUrl: 'https://www.bumper.com/vin-lookup/{vin}', optOutUrl: 'https://www.bumper.com/svc/optout/search/comprehensive_optouts', category: 'paid', lookupTypes: ['vin'] },
  { name: 'carfax.com', searchUrl: 'https://www.carfax.com/vehicle-history-reports/', optOutUrl: null, category: 'paid', lookupTypes: ['vin'], manual: true },
  { name: 'autocheck.com', searchUrl: 'https://www.autocheck.com/vehiclehistory/', optOutUrl: null, category: 'paid', lookupTypes: ['vin'], manual: true },
  { name: 'emailtracer.com', searchUrl: 'https://emailtracer.com/', optOutUrl: 'https://emailtracer.com/optout', category: 'paid', lookupTypes: ['email'], manual: true }
];
